name: build-swiftray-win64-installer
on: 
  #workflow_dispatch
  push:
    tags:
      - "w*.*.*"
jobs:
  setup-win-mingw-build-environment:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-make
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-python-conan
      #- name: Set 3GB compile memory
      #  shell: msys2 {0}
      #  run: |
      #    bcdedit /set IncreaseUserVa 3072

      - name: Build libpotrace
        shell: msys2 {0}
        run: |
          echo $PATH
          pwd
          cd third_party/libpotrace
          curl https://potrace.sourceforge.net/download/1.16/potrace-1.16.tar.gz -o potrace-1.16.tar.gz
          tar -xzvf potrace-1.16.tar.gz
          conan install . --build=missing
          conan build .
          conan create . user/testing

      #- name: Try OpenCV with conan
      #  run: |
      #    cd third_party/opencv
      #    conan install . --build=missing

      # vcpkg cache
      - name: Restore vcpkg and its artifacts.
        uses: actions/cache@v2
        id: vcpkg-cache
        with:
          path: |
            ${{ env.VCPKG_ROOT }}
            ${{ github.workspace }}/build/vcpkg_installed
            !${{ env.VCPKG_ROOT }}/.git
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          key: |
            ${{ hashFiles( 'vcpkg.json' ) }}-cache-key-v1
      # install vcpkg
      - name: Get vcpkg(windows)
        if: ${{ steps.vcpkg-cache.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ github.workspace }}
          mkdir build -force
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
      
      - name: install opencv (with vcpkg)
        if: ${{ steps.vcpkg-cache.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ github.workspace }}
          vcpkg install opencv:x64-windows

      - name: Install Qt5
        #if: ${{ steps.vcpkg-cache.outputs.cache-hit != 'true' }}
        run: |
          #cd ${{ github.workspace }}
          #vcpkg install qt5:x64-windows
          python3 -m pip install setuptools wheel
          python3 -m pip install py7zr
          python3 -m pip install aqtinstall==2.1.0
          python3 -m aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 -m debug_info -O ${{ github.workspace }}/Qt

      - name: Create build dir
        run: |
          mkdir build

      - name: Conan install
        run: |
          cd build
          conan install .. --build=missing
          ls
            
      - name: CMake
        run: |
          #cmake -B build -S . -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake -B build -S . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" -DOpenCV_DIR="${{ github.workspace }}\vcpkg\packages\opencv_x64-windows\share\opencv" -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/5.15.2/msvc2019_64/lib/cmake
      
      - name: Build
        run: |
          cmake --build build --config RelWithDebInfo --parallel

      #- name: Deploy
      #  shell: msys2 {0}
      #  run: |
      #    export PATH="/mingw64/bin:$PATH"
      #    windeployqt --qmldir src/windows/qml --compiler-runtime build/release/Swiftray.exe
      #- name: Copy necessary shared libraries
      #  shell: msys2 {0}
      #  run: |
      #- name: Create .msi installer
      #  run: |
