name: build-swiftray-win64-installer
on: 
  #workflow_dispatch
  push:
    tags:
      - "w*.*.*"
jobs:
  setup-win-mingw-build-environment:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-make
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-python-conan
      #- name: Set 3GB compile memory
      #  shell: msys2 {0}
      #  run: |
      #    bcdedit /set IncreaseUserVa 3072

      - name: Build
        shell: msys2 {0}
        run: |
          echo $PATH
          pwd
          cd third_party/libpotrace
          curl https://potrace.sourceforge.net/download/1.16/potrace-1.16.tar.gz -o potrace-1.16.tar.gz
          tar -xzvf potrace-1.16.tar.gz
          conan install . --build=missing
          conan build .
          conan create . user/testing
      #- name: Deploy
      #  shell: msys2 {0}
      #  run: |
      #    export PATH="/mingw64/bin:$PATH"
      #    windeployqt --qmldir src/windows/qml --compiler-runtime build/release/Swiftray.exe
      #- name: Copy necessary shared libraries
      #  shell: msys2 {0}
      #  run: |
      #- name: Create .msi installer
      #  run: |
