name: release-build
on:
  push:
    tags:
      - "s*.*.*"
  #workflow_dispatch:
  #inputs:
  #  name:
  #    Description: 'Build message'
  #    default: 'Hello'
  #    required: false
jobs:
  generate-appcast:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          #- { os: windows-latest }
          - { os: macos-12       }

    name: ${{matrix.cfg.os}}

    runs-on: ${{matrix.cfg.os}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download dmg file
        run: |
          curl https://swiftray.s3.ap-northeast-1.amazonaws.com/mac/swiftray_1.1.3.dmg -o swiftray_1.1.3.dmg
      
      - name: Download / Install Sparkle
        run: |
          curl -s "https://api.github.com/repos/sparkle-project/Sparkle/releases/latest" \
              | grep "browser_download_url.*.tar.xz" \
              | cut -d : -f 2,3 \
              | tr -d \" \
              | wget -i - -O Sparkle.tar.xz
          mkdir Sparkle
          cd Sparkle
          tar -xf ../Sparkle.tar.xz
          ls
      
      - name: Download source appcast.xml
        run: |
          curl https://swiftray.s3.ap-northeast-1.amazonaws.com/mac/swiftray_update_appcast_macOS.xml -o swiftray_update_appcast_macOS.xml
      
      - name: Get signing key
        env: 
          SPARKLE_SIGNING_KEY: ${{ secrets.SPARKLE_ED25519_SIGNING_KEY }}
        run: |
          echo $SPARKLE_SIGNING_KEY > sparkle_key.pem
      
      #- name: Try signing
      #  run: |
      #    /usr/local/Caskroom/sparkle/*/bin/sign_update -f sparkle_key.pem swiftray_1.1.3.dmg
      - name: Install lxml python package
        run: |
          pip3 install lxml

      - name: Run python script
        run: |
          python3 packaging/macOS/gen_appcast.py \
              --sparkle Sparkle \
              --signkey sparkle_key.pem \
              --dmg swiftray_1.1.3.dmg \
              --src_appcast swiftray_update_appcast_macOS.xml

